---
# configure the parameters replaced in jupyter notebooks when running on CI with papermill
# common parameters used in several notebooks:
epochs: 2
batch_size: 5
# short random walks
walk_length: 5
# minimal ensembles:
n_estimators: 2
n_predictions: 2
# reduce graph size for movielens-recommender.ipynb and calibration-pubmed-link-prediction.ipynb:
train_size: 0.005
test_size: 0.01
val_size: 0.01
# minimal metapaths for demos/embeddings/stellargraph-metapath2vec.ipynb:
metapaths: [["group", "group"], ["group", "user", "user", "group"]]
# minimal parameters for demos/interpretability/gat/node-link-importance-demo-gat.ipynb:
n_steps: 2
target_nid: 409725 # 2-hop ego net has 5 nodes
